In [ ]:
!pip install numpy --user

In [2]:
import numpy as np

In [3]:
# to get documentation about a function, press SHIFT + TAB

In [4]:
a = [1,2,3,'mani']
a1 = np.array([1,2,3])

In [51]:
array = np.arange(20)

In [52]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

a = [1,2]

In [55]:
a = [1,2]

In [53]:
2 * array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [10]:
array.shape

(20,)

In [13]:
array[10]

10

In [14]:
array[:3]

array([0, 1, 2])

In [15]:
array[3] = 100
print(array)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [16]:
array[3] ='Numpy'

ValueError: invalid literal for int() with base 10: 'Numpy'

In [17]:
normal_python_list = [1,2,3,4]

In [18]:
normal_python_list[2] = "Mani"

In [19]:
normal_python_list

[1, 2, 'Mani', 4]

In [ ]:
array.reshape

In [25]:
array = np.arange(30).reshape(2,5,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [26]:
# I want to access 22 using slicing
array[1][2][1]

22

In [21]:
array.shape

(4, 5)

In [22]:
array[2][4]

14

In [30]:
array1 = np.arange(27).reshape(3,3,3)
array1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
array1.shape

(3, 3, 3)

In [31]:
array.shape

(2, 5, 3)

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
x = np.array([[11, -2, 63], [4, 5, 6]])

In [29]:
x.shape

(2, 3)

In [41]:
import numpy as np 
  
in_arr1 = np.array([[1, 2, 3], 
                    [4, 5, 6]]) 

in_arr2 = np.array([[1, 0, -5], 
                    [3, 2, 1]]) 
   
print ("1st Input array : ", in_arr1)  
print ("2nd Input array : ", in_arr2)  

out_arr = np.add(in_arr1, in_arr2)  
print ("output added array : ", out_arr)

1st Input array :  [[1 2 3]
 [4 5 6]]
2nd Input array :  [[ 1  0 -5]
 [ 3  2  1]]
output added array :  [[ 2  2 -2]
 [ 7  7  7]]


In [36]:
in_arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
in_arr2

array([[ 1,  0, -5],
       [ 3,  2,  1]])

In [38]:
in_arr1 + in_arr2

array([[ 2,  2, -2],
       [ 7,  7,  7]])

In [35]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [45]:
import numpy as np 
  
in_arr1 = np.array([[1, 2, 3], [4, 5, 1]]) 
in_arr2 = np.array([[1, 0, 1], [3,0, 1]]) 
   
print ("1st Input array : ", in_arr1)  
print ("2nd Input array : ", in_arr2)  
    
out_arr = np.multiply(in_arr1, in_arr2)  
print ("output added array : ", out_arr)

1st Input array :  [[1 2 3]
 [4 5 1]]
2nd Input array :  [[1 0 1]
 [3 0 1]]
output added array :  [[ 1  0  3]
 [12  0  1]]


In [44]:
import numpy as np 
  
in_arr1 = np.array([[1, 2,3], [4, 5, 1]]) 
in_arr2 = np.array([[1, 0, -1], [3,0, 1]]) 
   
print ("1st Input array : ", in_arr1)  
print ("2nd Input array : ", in_arr2)  
    
out_arr = np.dot(in_arr1, in_arr2)  
print ("output added array : ", out_arr)

1st Input array :  [[1 2 3]
 [4 5 1]]
2nd Input array :  [[ 1  0 -1]
 [ 3  0  1]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
array = np.arange(20).reshape(4,6)
array

In [46]:
a = [1,2,3]
sum(a)

6

In [49]:
a.count(2)

1

In [50]:
np.sum(a)

6